import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import * as fs from "fs";

const docsDir = "./docs";
const componentsDir = `${docsDir}/components`;
const hooksDir = `${docsDir}/hooks`;
const utilsDir = `${docsDir}/utils`;

// 폴더에 있는 모든 파일을 가져옴
const componentsFiles = fs.readdirSync(componentsDir);
const hooksFiles = fs.readdirSync(hooksDir);
const utilsFiles = fs.readdirSync(utilsDir);
const cssFiles = fs.readdirSync(`${docsDir}/css`);
const booksFiles = fs.readdirSync(`${docsDir}/books`);
const svgFiles = fs.readdirSync(`${docsDir}/svg`);

const cutPrefixNumber = (fileName: string) => fileName.split("_")[1];
const cutSuffixMd = (fileName: string) => fileName.split(".")[0];
const convertToDoctitle = (fileName: string) =>
  cutSuffixMd(cutPrefixNumber(fileName));

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "svg tutorial",
      items: [...svgFiles.map((file) => `svg/${convertToDoctitle(file)}`)],
    },
    {
      type: "category",
      label: "css tutorial",
      items: [...cssFiles.map((file) => `css/${convertToDoctitle(file)}`)],
    },
  ],
  toolboxSidebar: [
    {
      type: "autogenerated",
      dirName: "toolbox",
    },
    {
      type: "category",
      label: "Components",
      items: [
        ...componentsFiles.map(
          (file) => `components/${convertToDoctitle(file)}`
        ),
      ],
    },
    {
      type: "category",
      label: "Hooks",
      items: [...hooksFiles.map((file) => `hooks/${convertToDoctitle(file)}`)],
    },
    {
      type: "category",
      label: "Utils",
      items: [...utilsFiles.map((file) => `utils/${convertToDoctitle(file)}`)],
    },
  ],
  booksSidebar: [
    {
      type: "autogenerated",
      dirName: "books",
    },
  ],
};

export default sidebars;
